#!/bin/bash

CONTAINER_NAME="spark_mon"
if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
	docker kill $CONTAINER_NAME
	docker rm $CONTAINER_NAME
fi
if [ -d "./logs" ];then
	rm -fr ./logs/*
fi

DATA_ROOT=/mnt/sda1/data

docker build -t jhu/spark:2.6 github.com/jhu-chang/docker-grafana-graphite.git
docker run -d -v $DATA_ROOT/kamon-grafana/log/supervisor:/var/log/supervisor -v $DATA_ROOT/kamon-grafana/log/graphite:/opt/graphite/storage/log  -v $DATA_ROOT/kamon-grafana/data/grafana:/opt/grafana/data  -v $DATA_ROOT/kamon-grafana/data/whisper:/opt/graphite/storage/whisper -p 80:80 -p 81:81 -p 8125:8125/udp -p 8126:8126 -p 2003:2003 --name ${CONTAINER_NAME} jhu/spark_mon:2.6 

# -v /mnt/sda1/data/kamon-grafana/data/whisper:/opt/graphite/storage/whisper
# -v /mnt/sda1/data/kamon-grafana/data/grafana:/opt/grafana/data 
# -v /mnt/sda1/data/kamon-grafana/log/graphite:/opt/graphite/storage/log 
