#! /bin/bash

docker kill spark
docker rm spark
truncate ./logs/* --size 0

docker build -t jhuu/spark github.com/jhu-chang/docker-grafana-graphite.git
docker run -d -v $(pwd)/logs:/var/log/supervisor -p 80:80 -p 8125:8125/udp -p 8126:8126 -p 2003:2003 --name spark jhuu/spark 

